name: Deploy Yard Frontend App to EC2

on:
  push:
    branches: [ main ]
    paths:
     - '**'
     - '!server/**'
     - '!landing/**'

jobs:
  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy frontend on EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            cd /home/ubuntu/60yard-admin &&
            git checkout main &&
            git fetch --all &&
            git pull origin main &&
            docker system prune -af &&
            docker-compose stop 60yard-frontend-app &&
            docker-compose rm -f 60yard-frontend-app &&
            docker-compose up -d --build 60yard-frontend-app
          '
